[package]
name = "berusty"
version = "0.1.1"
description = "Me practicing Rust"
authors = ["Poulad Ashrafpour <poulad.pld@gmail.com>"]
readme = "README.md"
license = "GPL-3.0"
license-file = "LICENSE"
homepage = "https://github.com/poulad/Berusty"
repository = "https://github.com/poulad/Berusty"
