[package]
name = "berusty"
version = "0.1.0"
description = "Me practicing Rust"
authors = ["Poulad Ashrafpour <poulad.pld@gmail.com>"]
license = "GPL-3.0"
readme = "README.md"
homepage = "https://github.com/poulad/Berusty"
repository = "https://github.com/poulad/Berusty"
